language: cpp
sudo: required
os:
  - linux
  - osx
compiler:
  - gcc
  - clang
matrix:
  include:
    - os: linux
      compiler: gcc
      env: COVERAGE="true"
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.7
    packages:
      - libreadline-dev
      - libncurses5-dev
      - g++-4.8
      - python-yaml
      - clang-format-3.7
      - clang-tidy-3.7
script:
  - tools/travis/${TRAVIS_OS_NAME}.sh
